### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Sbte** [Sbte/fix_matlab_eps#1]
Reported by @hk66 in https://github.com/altmany/export_fig/issues/44

@Sbte Thanks for your code. I wanted to use your python code for an .eps file which has not been generated by matlab(attached here). I have this error:
"Traceback (most recent call last):
File "fix_matlab_eps.py", line 121, in
main()
File "fix_matlab_eps.py", line 56, in main
up_to_m = last[0].split('m')[0]
IndexError: list index out of range"

Could you please check it?
[test.eps.zip](https://github.com/altmany/export_fig/files/150597/test.eps.zip)

**Comment by hk66** [comment]
Thanks. The error has been solved, but the white lines are still remained in the red part of the figure!

**Comment by Sbte** [comment]
Ok, I'll have a look tomorrow. At this machine I don't see them but maybe at another I do. I created #2 for this.
