### ISSUE TITLE
White lines remain in surface plots

### ISSUE THREAD

**Issue by Sbte** [Sbte/fix_matlab_eps#2]
[test.eps.zip](https://github.com/altmany/export_fig/files/150597/test.eps.zip)

There are still white lines in the red part of the figure. I don't see this in evince 3.10.3.

**Comment by Sbte** [comment]
Oh, forgot to convert to PDF. I see them now

**Comment by Sbte** [comment]
Ok I think I understand why this happens. It is because there are overlapping colors. The colorbar is on top of the red plane. So when I try to merge the red parts, there are parts of another color in between. I can't just merge all elements of the same color, because then you could not have separate planes anymore like in the example in the README. Actually I'm not even sure if I can fix this without knowledge about the geometry.

**Comment by Sbte** [comment]
Ok so here is what I might try. If the first number of some patch also occurs in another patch of the same color, then I merge them. This does, however, require me to make some sort of drawing queue that knows what is on top of what.

**Comment by hk66** [comment]
I avoided having colorbar on top of the surface plot.  Nevertheless, I still have those white lines(attached here). Also I tried with a more complicated geometry and I can see these remained white lines in all sections of structure!
[test2.eps.zip](https://github.com/Sbte/fix_matlab_eps/files/154286/test2.eps.zip)

**Comment by Sbte** [comment]
Ok, thanks for debugging this. I think then the problem might be different. In the middle between blue and red, there are some really really small triangles that look like this

```
0 0.133333 1 rg
637.5 242.418 m 637.816 242.418 l 637.816 222.059 l h
637.5 242.418 m f
0 0.290196 1 rg
637.816 242.418 m 637.941 242.418 l 637.941 214.207 l h
637.816 222.059 m 637.816 242.418 l 637.941 214.207 l h
637.816 222.059 m f
0 0.47451 1 rg
637.941 242.418 m 637.988 242.418 l 637.988 211.176 l h
637.941 214.207 m 637.941 242.418 l 637.988 211.176 l h
637.941 214.207 m f
0 0.658824 1 rg
637.988 242.418 m 638.008 242.418 l 638.008 210.008 l h
637.988 211.176 m 637.988 242.418 l 638.008 210.008 l h
637.988 211.176 m f
0 0.823529 1 rg
638.008 242.418 m 638.012 242.418 l 638.012 209.555 l h
638.008 210.008 m 638.008 242.418 l 638.012 209.555 l h
638.008 210.008 m f
0 1 0.976471 rg
638.016 242.418 m 638.02 242.418 l 638.02 209.289 l h
638.016 242.418 m f
1 0.823529 0 rg
638.023 242.418 m 638.027 242.418 l 638.027 208.535 l h
638.023 208.988 m 638.023 242.418 l 638.027 208.535 l h
638.023 208.988 m f
1 0.658824 0 rg
638.027 242.418 m 638.047 242.418 l 638.047 207.367 l h
638.027 208.535 m 638.027 242.418 l 638.047 207.367 l h
638.027 208.535 m f
1 0.47451 0 rg
638.047 242.418 m 638.094 242.418 l 638.094 204.34 l h
638.047 207.367 m 638.047 242.418 l 638.094 204.34 l h
638.047 207.367 m f
1 0.290196 0 rg
638.094 242.418 m 638.219 242.418 l 638.219 196.484 l h
638.094 204.34 m 638.094 242.418 l 638.219 196.484 l h
638.094 204.34 m f
1 0.133333 0 rg
638.219 242.418 m 638.535 242.418 l 638.535 176.125 l h
638.219 196.484 m 638.219 242.418 l 638.535 176.125 l h
638.219 196.484 m f
```

so that looks like a transition from blue to red. If I remove those there are small white triangles on the border, but the plane itself doesn't have lines. My code can actually only cope with patches of a uniform color (like a contour plot), which is why this causes problems. Writing the code in the way I described above might still help though. Note that I will probably never be able to remove white lines between different colors, so even if I fix this, this transition might still look weird. You can probably also see this if you plot a gradient over the whole domain.

**Comment by hk66** [comment]
In these surface plots I always have gradient and it is normal in them to have non-uniform colour in one cell (because colour data always is the interpolation of the value on the grid nodes). 
So by your descriptions, I guess it is not possible to use your code for fixing the problem in this kind of surface plot!

**Comment by Sbte** [comment]
No, I'm sorry, but I think it is either not possible or at least very hard. I really hope that they fix it in Matlab soon. I'll still leave this issue open to see if I can find a way to also handle surface plots nicely.

**Comment by hk66** [comment]
Thanks. But my problem can not be fixed by matlab, because my figure is generated in another software. Have you seen any other solution for this problem(even to fix it manually)?

**Comment by Sbte** [comment]
You can open it in Inkscape and then select the different triangles and merge them using Ctrl+K. You can for instance select them using the XML editor (Shift+Ctrl+X) and selecting by color (Ctrl+F and in style put fill:#ff0800 for the red part). I hope it helps.

I'll close this issue as my program is just a quick fix I made for Matlab generated contour plots.
