### ISSUE TITLE
Removes colorbar

### ISSUE THREAD

**Issue by jkurelek** [Sbte/fix_matlab_eps#3]
Hey. First off, thanks for creating this script. I've been able to use it (mostly) successfully. However it has been struggling with the following eps (in.eps), as the colorbar colors and numbers are gone after running the script on it (out.eps).

[test.zip](https://github.com/Sbte/fix_matlab_eps/files/243172/test.zip)

Also as a side note. When first running your script on this particular eps, I was getting this Inkscape error

`** (inkscape.exe:3220): WARNING **: EPS cannot have its bounding box extend beyond its content, so if your drawing is smaller than the page, --export-area-page will clip it to drawing.`

Presumably because this eps is actually larger than its page. Modifying line 23 in your code to 

`ret = subprocess.call('inkscape --export-area-drawing --export-eps=' +
                          tmp+' '+sys.argv[1], shell=True)`

fixed it.

Cheers

**Comment by Sbte** [comment]
It seems like your version of cairo (which is used by inkscape) is older than mine (v1.11.2 vs v1.13.1). For me it actually gives the correct output. So I presume updating cairo and/or inkscape will fix the problem.

However, I did find a problem and will try to fix that. I will try to do that with the output files you provided or else I'll implement a `--debug` argument to the script and ask you for the output from that.

The reason I use `--export-area-page` is so you don't get extra white space around the image (which you usually don't want. I think `--export-area-drawing` actually did add extra white space for me.
